name: Docker Image CI

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

env:
  DOCKER_IMAGE_NAME: geo-guardian

jobs:
  build-linux:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
            
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get the tag name
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image (Linux)
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/riscv64,linux/ppc64le,linux/s390x
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest

  build-windows:
  
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
            
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get the tag name
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Build and push Docker image (Windows Server Core)
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile.windows
          platforms: windows/amd64
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}-windows
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:windows-latest

      - name: Build and push Docker image (Windows Nano Server)
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile.windows.nano
          platforms: windows/amd64
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}-nanoserver
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:nanoserver-latest
